### ISSUE TITLE
Rstudio image now out of date.

### ISSUE THREAD

**Issue by da11an** [openanalytics/shinyproxy-rstudio-ide-demo#6]
The openanalytics/shinyproxy-rstudio-ide-demo:2021.09.2_382__4.1.2 image is now a bit out of date with RStudio 2022.12.0+353 released December 15th, 2022. Create a new image for the latest version.

**Comment by LEDfan** [comment]
Hi

I have updated the image to latest R and RStudio versions. Note that it's should be easy to do this yourselves in any case.
